# Generated by Django 4.0 on 2022-01-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('natijaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foydalanivchi',
            new_name='Foydalanuvchi',
        ),
    ]
